LIST_PROFILE_PROTO_TYPE = [
    "bigproto",
    "tcp",
    "udp",
    "fasthttp",
    "sctp",
    "ipother",
]

PROFILES_PROTOCOL_IGNORE = [
    "apm-forwarding-fastL4",
    "fastL4",
    "full-acceleration",
    "security-fastL4",
    "fasthttp",
    "apm-forwarding-client-tcp",
    "apm-forwarding-server-tcp",
    "f5-tcp-lan",
    "f5-tcp-mobile",
    "f5-tcp-progressive",
    "f5-tcp-wan",
    "mptcp-mobile-optimized",
    "splitsession-default-tcp",
    "tcp",
    "tcp-lan-optimized",
    "tcp-legacy",
    "tcp-mobile-optimized",
    "tcp-wan-optimized",
    "wom-tcp-lan-optimized",
    "wom-tcp-wan-optimized",
    "udp",
    "udp_decrement_ttl",
    "udp_gtm_dns",
    "udp_preserve_ttl",
    "sctp",
    "ipother",
]

LIST_PROFILE_TYPES = [
    "http",
    "httpcompression",
    "webacceleration",
    "ftp",
    "tftp",
    "dns",
    "rtsp",
    "icap",
    "requestadapt",
    "responseadapt",
    "diameter",
    "dhcpv4",
    "dhcpv6",
    "radius",
    "sipp",
    "smtp",
    "smtps",
    "clientldap",
    "serverldap",
    "isession",
    "rewrite",
    "xml",
    "http2",
    "http3",
    "quic",
    "socks",
    "fix",
    "gtp",
    "pptp",
    "websocket",
    "ipsecalg",
    "netflow",
    "imap",
    "pop3",
    "ocsp",
]

PROFILES_SERVICES_IGNORE = [
    "http",
    "http-explicit",
    "http-transparent",
    "httpcompression",
    "wan-optimized-compression",
    "apm-enduser-if-cache",
    "optimized-acceleration",
    "optimized-caching",
    "webacceleration",
    "ftp",
    "tftp",
    "dns",
    "rtsp",
    "icap",
    "requestadapt",
    "responseadapt",
    "diameter",
    "dhcpv4",
    "dhcpv4_fwd",
    "dhcpv6",
    "dhcpv6_fwd",
    "radiusLB",
    "radiusLB-subscriber-aware",
    "sip",
    "smtp",
    "smtps",
    "clientldap",
    "serverldap",
    "isession",
    "isession-encrypt",
    "isession-softwoc",
    "rewrite",
    "rewrite-portal",
    "rewrite-uri-translation",
    "xml",
    "http2",
    "http3",
    "quic",
    "socks",
    "fix",
    "gtp",
    "pptp",
    "websocket",
    "ipsecalg",
    "netflow",
    "imap",
    "pop3",
    "ocsp",
]

PROFILES_SSL_IGNORE = [
    "clientssl",
    "clientssl-insecure-compatible",
    "clientssl-quic",
    "clientssl-secure",
    "crypto-server-default-clientssl",
    "splitsession-default-clientssl",
    "wom-default-clientssl",
    "apm-default-serverssl",
    "cloud-service-default-ssl",
    "crypto-client-default-serverssl",
    "do-not-remove-without-replacement",
    "f5aas-default-ssl",
    "pcoip-default-serverssl",
    "serverssl",
    "serverssl-insecure-compatible",
    "serverssl-secure",
    "shape-api-ssl",
    "splitsession-default-serverssl",
    "wom-default-serverssl",
]

PROFILES_PERSIST_IGNORE = [
    "cookie",
    "dest_addr",
    "hash",
    "host",
    "msrdp",
    "sip_info",
    "source_addr",
    "ssl",
    "universal",
]

PROFILES_OTHERS = [
    "profile_connpool",
    "profile_statistics",
    "profile_stream",
    "profile_reqlog",
    "dns_logging_options",
    "alg_log_profile",
    "profile_nat_stats_config",
    "profile_http_proxy_connect",
    "profile_connector",
    "profile_service",
    "profile_tdr",
    "profile_doh_proxy",
    "profile_doh_server",
]

PROFILES_OTHERS_API = {
    "profile_connpool": "one-connect",
    "profile_statistics": "statistics",
    "profile_stream": "stream",
    "profile_reqlog": "request-log",
    "dns_logging_options": "dns-logging",
    "alg_log_profile": "",
    "profile_nat_stats_config": "",
    "profile_http_proxy_connect": "http-proxy-connect",
    "profile_connector": "connector",
    "profile_service": "service",
    "profile_tdr": "tdr",
    "profile_doh_proxy": "doh-proxy",
    "profile_doh_server": "doh-server",
}

PROFILES_OTHER_IGNORE = [
    "oneconnect",
    "stats",
    "stream",
    "request-log",
    "profile-dns",
    "alg_log_profile",
    "nat-stats",
    "http-proxy-connect",
    "connector",
    "access-logonpage-protection-connector",
    "access-logonpage-protection-service",
    "service",
    "mapt",
    "tdr",
    "tdr-diameter",
    "tdr-diameter",
    "tdr-sip",
    "doh-proxy",
    "doh-server",
]
