from handler.ltm.ltm import Ltm
from handler.ltm.models import (
    NatModel,
    PoolModel,
    SnatModel,
    MonitorModel,
    PoliciesModel,
    SnatpoolModel,
    DataGroupModel,
    ProfilesSSLModel,
    ProfilesOtherModel,
    VirtualServersModel,
    ProfilesPersistModel,
    ProfilesProtocolModel,
    ProfilesServicesModel,
    iRuleModel,
)
from handler.system.models import (
    UserModel,
    FolderModel,
    UserAlertModel,
    TrafficGroupModel,
    iCallModel,
)
from handler.network.models import (
    TrunkModel,
    VlansModel,
    SelfIpModel,
    StaticRouteModel,
    RoutesDomaninModel,
)
from handler.ltm.generic_message.models import (
    PeerModel,
    RouteModel,
    RouterModel,
    ProtocolModel,
    GmTransportConfigModel,
)

ltm = Ltm()

MODELS = {
    "pool": PoolModel,
    "virtual_server": VirtualServersModel,
    "irule": iRuleModel,
    "datagroup": DataGroupModel,
    "monitor": MonitorModel,
    "profiles_ssl": ProfilesSSLModel,
    "profiles_services": ProfilesServicesModel,
    "profiles_persist": ProfilesPersistModel,
    "profiles_other": ProfilesOtherModel,
    "profiles_protocol": ProfilesProtocolModel,
    "policies": PoliciesModel,
    "snat": SnatModel,
    "snat_pool": SnatpoolModel,
    "nat": NatModel,
    "self_ip": SelfIpModel,
    "vlan": VlansModel,
    "trunks": TrunkModel,
    "static_route": StaticRouteModel,
    "peer": PeerModel,
    "protocol": ProtocolModel,
    "router": RouterModel,
    "route": RouteModel,
    "transport_config": GmTransportConfigModel,
    "user_alert": UserAlertModel,
    "user": UserModel,
    "icall": iCallModel,
    "traffic_group": TrafficGroupModel,
    "folder": FolderModel,
    "route_domain": RoutesDomaninModel,
}


IMPORT_CONFIG = {
    "user_alert": 1,
    "vlan": 1,
    "traffic_group": 1,
    "folder": 2,
    "trunks": 2,
    "default": 2,
    "route_domain": 3,
    "nat": 4,
    "snat": 4,
    "snat_pool": 4,
    "profiles_ssl": 4,
    "profiles_services": 4,
    "profiles_persist": 4,
    "profiles_other": 4,
    "profiles_protocol": 4,
    "policies": 4,
    "monitor": 4,
    "self_ip": 4,
    "datagroup": 5,
    "irule": 5,
    "static_route": 6,
    "icall": 4,
    "pool": 5,
    "protocol": 6,
    "transport_config": 7,
    "peer": 8,
    "route": 9,
    "router": 10,
    "virtual_server": 11,
}
